#############################################################################
# Makefile for building: DrawMips
# Generated by qmake (2.01a) (Qt 4.8.6) on: Wed Sep 24 22:15:48 2014
# Project:  DrawMips.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.6/bin/qmake -o Makefile DrawMips.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O0 -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O0 -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.6/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.8.6/include/QtCore -I/usr/local/Trolltech/Qt-4.8.6/include/QtGui -I/usr/local/Trolltech/Qt-4.8.6/include -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.6/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.6/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.8.6/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = DrawMips.cc \
		RectHelpers.cc \
		Memory.cc \
		qdisplay.cc \
		CPU.cc \
		Computer.cc \
		Instruction.cc \
		ALU.cc \
		TimeButton.cc moc_qdisplay.cpp \
		moc_ALU.cpp \
		moc_TimeButton.cpp
OBJECTS       = DrawMips.o \
		RectHelpers.o \
		Memory.o \
		qdisplay.o \
		CPU.o \
		Computer.o \
		Instruction.o \
		ALU.o \
		TimeButton.o \
		moc_qdisplay.o \
		moc_ALU.o \
		moc_TimeButton.o
DIST          = /usr/local/Trolltech/Qt-4.8.6/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/include_source_dir.prf \
		DrawMips.pro
QMAKE_TARGET  = DrawMips
DESTDIR       = 
TARGET        = DrawMips

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DrawMips.pro  /usr/local/Trolltech/Qt-4.8.6/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.8.6/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile DrawMips.pro
/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.6/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile DrawMips.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/DrawMips1.0.0 || $(MKDIR) .tmp/DrawMips1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/DrawMips1.0.0/ && $(COPY_FILE) --parents qdisplay.h RectHelpers.h Memory.h CPU.h Computer.h Instruction.h ALU.h TimeButton.h .tmp/DrawMips1.0.0/ && $(COPY_FILE) --parents DrawMips.cc RectHelpers.cc Memory.cc qdisplay.cc CPU.cc Computer.cc Instruction.cc ALU.cc TimeButton.cc .tmp/DrawMips1.0.0/ && (cd `dirname .tmp/DrawMips1.0.0` && $(TAR) DrawMips1.0.0.tar DrawMips1.0.0 && $(COMPRESS) DrawMips1.0.0.tar) && $(MOVE) `dirname .tmp/DrawMips1.0.0`/DrawMips1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/DrawMips1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

/usr/local/Trolltech/Qt-4.8.6/bin/moc:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qdisplay.cpp moc_ALU.cpp moc_TimeButton.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qdisplay.cpp moc_ALU.cpp moc_TimeButton.cpp
moc_qdisplay.cpp: qdisplay.h \
		/usr/local/Trolltech/Qt-4.8.6/bin/moc
	/usr/local/Trolltech/Qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) qdisplay.h -o moc_qdisplay.cpp

moc_ALU.cpp: ALU.h \
		/usr/local/Trolltech/Qt-4.8.6/bin/moc
	/usr/local/Trolltech/Qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) ALU.h -o moc_ALU.cpp

moc_TimeButton.cpp: TimeButton.h \
		/usr/local/Trolltech/Qt-4.8.6/bin/moc
	/usr/local/Trolltech/Qt-4.8.6/bin/moc $(DEFINES) $(INCPATH) TimeButton.h -o moc_TimeButton.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

DrawMips.o: DrawMips.cc qdisplay.h \
		Computer.h \
		CPU.h \
		Memory.h \
		ALU.h \
		TimeButton.h \
		Instruction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DrawMips.o DrawMips.cc

RectHelpers.o: RectHelpers.cc RectHelpers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RectHelpers.o RectHelpers.cc

Memory.o: Memory.cc Memory.h \
		RectHelpers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Memory.o Memory.cc

qdisplay.o: qdisplay.cc qdisplay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qdisplay.o qdisplay.cc

CPU.o: CPU.cc CPU.h \
		Memory.h \
		RectHelpers.h \
		Computer.h \
		ALU.h \
		TimeButton.h \
		Instruction.h \
		qdisplay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CPU.o CPU.cc

Computer.o: Computer.cc Computer.h \
		CPU.h \
		Memory.h \
		ALU.h \
		TimeButton.h \
		RectHelpers.h \
		qdisplay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Computer.o Computer.cc

Instruction.o: Instruction.cc Instruction.h \
		Memory.h \
		Computer.h \
		CPU.h \
		ALU.h \
		TimeButton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Instruction.o Instruction.cc

ALU.o: ALU.cc ALU.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ALU.o ALU.cc

TimeButton.o: TimeButton.cc TimeButton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TimeButton.o TimeButton.cc

moc_qdisplay.o: moc_qdisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qdisplay.o moc_qdisplay.cpp

moc_ALU.o: moc_ALU.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ALU.o moc_ALU.cpp

moc_TimeButton.o: moc_TimeButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TimeButton.o moc_TimeButton.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

